name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]

jobs:
  test:
    name: 'Test (${{ matrix.node-version }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16']
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - uses: actions/setup-node@v3
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm lint

      - run: pnpm test --coverage
